/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.75
 * Generated at: 2017-04-21 05:29:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.mainBody.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class customBusinessOpportunity_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<input type=\"hidden\" name=\"customId\" value=\"\">\r\n");
      out.write("<input type=\"hidden\" name=\"businessOpportunityId\" value=\"\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("\t<div class=\"row-fluid\">\r\n");
      out.write("\t\t<div class=\"span12\">\r\n");
      out.write("\t\t\t<h3 class=\"page-title\">客户商机</h3>\r\n");
      out.write("\t\t\t<ul class=\"breadcrumb\">\r\n");
      out.write("\t\t\t\t<li>商机 <span class=\"divider\">/</span></li>\r\n");
      out.write("\t\t\t\t<li>客户商机</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- \r\n");
      out.write("\t<div class=\"row-fluid\">\r\n");
      out.write("\t\t<div class=\"span12\">\r\n");
      out.write("\t\t\t<div class=\"clearfix\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"btn-group\">\r\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-info\" style=\"width:100px;\">\r\n");
      out.write("\t\t\t\t\t\t所有商机 <i class=\"icon-plus\"></i>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"btn-group\">\r\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-success\" style=\"width:130px;\">\r\n");
      out.write("\t\t\t\t\t\t客户所有商机 <i class=\"icon-plus\"></i>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"btn-group\">\r\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-success\" style=\"width:130px;\">\r\n");
      out.write("\t\t\t\t\t\t任务列表 <i class=\"icon-plus\"></i>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"space15\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write(" -->\r\n");
      out.write("\t<div class=\"row-fluid\">\r\n");
      out.write("\t\t<div class=\"row-fluid\">\r\n");
      out.write("\t\t\t<!-- 客户信息 begin -->\r\n");
      out.write("\t\t\t<div class=\"span6\">\r\n");
      out.write("\t\t\t\t<div class=\"widget green\">\r\n");
      out.write("\t\t\t\t\t<div class=\"widget-title\">\r\n");
      out.write("\t\t\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"icon-reorder\"> </i> 客户信息\r\n");
      out.write("\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"widget-body\" >\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row-fluid\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\" profile span12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"span3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"javascript:(void)\" class=\"profile-features active\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\" icon-user\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p class=\"info\">客户资料</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"span1\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"span8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"row-fluid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"span12 bio\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<h2><span name=\"customName\">天阳宏业科技股份有限公司厦门分公司</span></h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"space10\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div style=\"margin-bottom:15px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div style=\"width:60px;display:block;float:left;\">联系人 : </div> <div name=\"customLinkmanName\" style=\"width:240px; display:block;float:left;\"> 白植伟</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"space10\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div style=\"margin-bottom:15px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div style=\"width:60px;display:block;float:left;\">职务 : </div> <div name=\"customLinkmanPost\" style=\"width:240px; display:block;float:left;\">业务部经理</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"space10\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div style=\"margin-bottom:15px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div style=\"width:60px;display:block;float:left;\">手机 : </div> <div name=\"customLinkmanPhone\" style=\"width:240px; display:block;float:left;\"> 18820331121</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"space10\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div style=\"margin-bottom:15px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div style=\"width:60px;display:block;float:left;\">住址 : </div> <div name=\"customAddress\" style=\"width:240px; display:block;float:left;\">福建省厦门市软件园二期望海路59号之二701室</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"space10\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div style=\"margin-bottom:15px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div style=\"width:60px;display:block;float:left;\">备注 : </div> <div name=\"customLinkmanRemark\" style=\"width:240px;display:block;float:left;\">软件公司，主要做金融业务。业务广，客户多。需要CRM管理客户关系。</div>..\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"space10\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- /客户信息 /end -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- 商机信息 begin -->\r\n");
      out.write("\t\t\t<div class=\"span6\">\r\n");
      out.write("\t\t\t\t<div class=\"widget red\">\r\n");
      out.write("\t\t\t\t\t<div class=\"widget-title\">\r\n");
      out.write("\t\t\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"icon-reorder\"></i> 商机信息\r\n");
      out.write("\t\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"widget-body\" style=\"height:320px;\">\r\n");
      out.write("\t\t\t\t\t\t<table\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"table table-striped table-advance table-bordered table-hover\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-table=\"memberInformation\">\r\n");
      out.write("\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th style=\"width:30%;\">名称</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th style=\"width:70%;\">内容</th>\r\n");
      out.write("\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr class=\"odd gradex\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>产品名称</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><span name=\"productName\">一米软件</span></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr class=\"odd gradex\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>跟进人</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><span name=\"employeeRealName\">梁伯昭</span></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr class=\"odd gradex\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>所属部门</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><span name=\"departmentName\">销售1部</span></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr class=\"odd gradex\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>预计销售金额(￥)</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><span name=\"preSalesAmount\">99921.00</span></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr class=\"odd gradex\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>预计成交时间</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><span name=\"preDealTime\">2017/5</span></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr class=\"odd gradex\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>销售阶段</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><span name=\"salesStageName\">初步沟通(10%)</span></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr class=\"odd gradex\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>备注</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td><span name=\"remark\">该公司需要定制一些新的功能，需要少许的改动。</span></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- /商机信息 /end -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 任务进度 begin -->\r\n");
      out.write("\t<div class=\"row-fluid\">\r\n");
      out.write("\t\t<div class=\"widget purple\">\r\n");
      out.write("\t\t\t<div class=\"widget-title\">\r\n");
      out.write("\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t<i class=\"icon-tasks\"></i> 任务进度\r\n");
      out.write("\t\t\t\t</h4>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"widget-body\">\r\n");
      out.write("\t\t\t\t<ul class=\"unstyled\">\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"btn btn-inverse\"> \r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"icon-check\"></i>\r\n");
      out.write("\t\t\t\t\t\t</span> \r\n");
      out.write("\t\t\t\t\t\t任务已经完成 <strong class=\"label label-info\"><span name=\"rateOfProgress\">85</span>%</strong>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"space10\"></div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"progress progress-success progress-striped active\">\r\n");
      out.write("\t\t\t\t\t\t\t<div data-rateOfProgress=\"rateOfProgress\" style=\"width: 85%;\" class=\"bar\"></div>\r\n");
      out.write("\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- /任务进度 /end -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- 任务反馈 begin -->\r\n");
      out.write("\t<div class=\"row-fluid\">\r\n");
      out.write("\t\t<div class=\"span12\">\r\n");
      out.write("\t\t\t<div class=\"widget red\">\r\n");
      out.write("\t\t\t\t<div class=\"widget-title\">\r\n");
      out.write("\t\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t<i class=\"icon-comments-alt\"></i>任务反馈\r\n");
      out.write("\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"widget-body\">\r\n");
      out.write("\t\t\t\t\t<div class=\"timeline-messages\" data-timeLine=\"feedback\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"msg-time-chat\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"message-img\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/mainBody/img/jpg/avatar1.jpg\" class=\"avatar\">\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"message-body msg-in\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"arrow\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"attribution\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">Jhon Doe</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tat 1:55pm, 13th April 2013\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Hello, How are you brother?</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"msg-time-chat\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"message-img\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/mainBody/img/jpg/avatar2.jpg\" class=\"avatar\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"message-body msg-out\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"arrow\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"attribution\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">Jonathan Smith</a> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tat 2:01pm, 13th April 2013\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>I'm Fine, Thank you. What about you? How is going on?</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"msg-time-chat\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"message-img\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t<img alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/mainBody/img/jpg/avatar1.jpg\" class=\"avatar\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"message-body msg-in\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"arrow\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"attribution\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">Jhon Doe</a> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tat 2:03pm, 13th April 2013\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>Yeah I'm fine too. Everything is going fine here.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"msg-time-chat\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"message-img\" href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t<img alt=\"\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/mainBody/img/jpg/avatar2.jpg\" class=\"avatar\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"message-body msg-out\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"arrow\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"attribution\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<a href=\"#\">Jonathan Smith</a> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tat 2:05pm, 13th April 2013\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\twell good to know that. anyway how much time you need to done your task?\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- /任务反馈 /end -->\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
