/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.75
 * Generated at: 2017-04-21 09:00:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.mainBody.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class detailCustom_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("\t<div class=\"row-fluid\">\r\n");
      out.write("\t\t<div class=\"span12\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<h3 class=\"page-title\">客户详情</h3>\r\n");
      out.write("\t\t\t<ul class=\"breadcrumb\">\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">客户管理</a> <span class=\"divider\">/</span></li>\r\n");
      out.write("\t\t\t\t<li class=\"active\">客户详情</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"row-fluid\">\r\n");
      out.write("\t\t<div class=\"span12\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"widget orange\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"widget-title\">\r\n");
      out.write("\t\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t<i class=\"icon-reorder\"></i> 客户详情\r\n");
      out.write("\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"widget-body\">\r\n");
      out.write("\t\t\t\t\t<div class=\"bs-docs-example\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"customId\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"nav nav-tabs\">\r\n");
      out.write("\t\t\t\t\t\t\t<li class=\"active\"><a data-toggle=\"tab\" href=\"#home\" onclick=\"datailCustomShow();\">客户信息</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a data-toggle=\"tab\" href=\"#profile\" onclick=\"getCustomBusinessOpportunity();\">客户商机</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"tab-content\" style=\"min-height:350px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"home\" class=\"tab-pane fade in active\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"row-fluid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\" profile span12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"span2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:(void)\" class=\"profile-features active\"> <i\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\" icon-user\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<p class=\"info\">基本信息</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"span10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"row-fluid\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"span8 bio\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<h2><span name=\"customName\">黄河森</span></h2>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label>地址 </label>: <span name=\"customAddress\">福建省厦门市集美区软件园三期</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label>联系人 </label>: <span name=\"customLinkmanName\">黄河森</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label>职务 </label>: <span name=\"customLinkmanPost\">菜鸡</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label>电话 </label>: <span name=\"customLinkmanPhone\">12987657867</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label>部门</label>: <span name=\"departmentName\">销售 1 部</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label>级别 </label>: <span name=\"customStateName\">普通</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label>状态 </label>: <span name=\"customRankName\">小型客户</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<label>备注 </label>: <span name=\"customLinkmanRemark\">没什么卵用</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"space5\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"profile\" class=\"tab-pane fade\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<table\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"table table-striped table-advance table-bordered table-hover\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-custom=\"businessOpportunityInfos\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>产品名称</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>预计销售金额(￥)</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>预计成交时间</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>销售阶段</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>跟进人</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th style=\"width: 200px;overflow: hidden;\">备注</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th>详情</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr class=\"odd gradex\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>一米软件</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>1908299.00</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>2017/3/30</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td><span class=\"label label-success\">初步沟通(10%)</span></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>张三</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>需要更改系统，添加新的功能</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td style=\"width:6%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-success\" onclick=\"showCustomBusinessOpportunity();\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"icon-tags\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<tr class=\"odd gradex\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>和兴农业系统</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>345231.00</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>2017/4/10</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td><span class=\"label label-warning\">谈判(50%)</span></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>李四</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td>系统完善，部署维护即可 系统完善，部署维护即可系统完善，部署维护即可系统完善，部署维护即可</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<td style=\"width:6%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-success\" onclick=\"showCustomBusinessOpportunity();\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"icon-tags\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
