/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.75
 * Generated at: 2017-04-21 08:57:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.mainBody.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class receiveTaskInformation_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"row-fluid\">\r\n");
      out.write("\t\t<div class=\"span12\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<h3 class=\"page-title\">收到的任务</h3>\r\n");
      out.write("\t\t\t<ul class=\"breadcrumb\">\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">任务</a> <span class=\"divider\">/</span></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">收到的任务</a> <span class=\"divider\">/</span></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 查看任务 begin -->\r\n");
      out.write("\t<div class=\"row-fluid\" data-task=\"receiveTask\">\r\n");
      out.write("\t\t<div class=\"span12\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"widget green\">\r\n");
      out.write("\t\t\t\t<div class=\"widget-title\">\r\n");
      out.write("\t\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t<i class=\"icon-reorder\"></i> 任务\r\n");
      out.write("\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"widget-body\">\r\n");
      out.write("\t\t\t\t\t<table\r\n");
      out.write("\t\t\t\t\t\tclass=\"table table-striped table-advance table-bordered table-hover\"\r\n");
      out.write("\t\t\t\t\t\tdata-task=\"receiveTask\">\r\n");
      out.write("\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t<th>任务内容</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>创建时间</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>开始日期</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>截止日期</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>创建人</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>执行者</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th style=\"width:8%\">状态</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th style=\"width:8%\">反馈</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th style=\"width:8%\">商机</th>\r\n");
      out.write("\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t<tr class=\"odd gradex\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>第一次发布任务</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>2017-03-21</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>2017-03-21</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>2017-04-01</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>王五</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>李四</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>未完成</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td style=\"width: 6%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"btn btn-success\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonclick=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"icon-tags\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td style=\"width: 6%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"btn btn-success\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonclick=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"icon-tags\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr class=\"odd gradex\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>第二次发布任务</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>2017-03-22</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>2017-03-22</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>2017-04-11</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>王五</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>张三</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>未完成</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td style=\"width: 6%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"btn btn-success\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonclick=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"icon-tags\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td style=\"width: 6%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"btn btn-success\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tonclick=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"icon-tags\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- /查看任务 /end -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 任务反馈 begin -->\r\n");
      out.write("\t<div class=\"row-fluid\" data-feedback=\"addFeedback\">\r\n");
      out.write("\t\t<div class=\"span12\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"widget green\">\r\n");
      out.write("\t\t\t\t<div class=\"widget-title\">\r\n");
      out.write("\t\t\t\t\t<h4>\r\n");
      out.write("\t\t\t\t\t\t<i class=\"icon-reorder\"></i> 任务反馈\r\n");
      out.write("\t\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"widget-body\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<form style=\"margin-left:10px;\" action=\"#\" class=\"form-horizontal\" data-feedback=\"addFeedback\" onsubmit=\"return false;\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"taskId\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" name=\"reEmployeeId\" value=\"\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"control-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"control-label\">任务内容</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"controls\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<textarea name=\"taskContent\" class=\"span6 ckeditor\" rows=\"6\" readonly=\"readonly\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"control-group\">\r\n");
      out.write("\t\t\t                <label class=\"control-label\">任务开始时间</label>\r\n");
      out.write("\t\t\t                <div class=\"controls input-group date\" name=\"taskStartTime\" >\r\n");
      out.write("\t\t\t                    <div class=\"input-prepend input-append\">\r\n");
      out.write("\t\t\t\t                    <input name=\"taskStartTime\" class=\"form-control\" size=\"16\" type=\"text\" readonly=\"readonly\">\r\n");
      out.write("\t\t\t\t                    <span class=\"input-group-addon\"><span class=\"glyphicon glyphicon-remove\"></span></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"input-group-addon\"><span class=\"glyphicon glyphicon-calendar\"></span></span>\r\n");
      out.write("\t\t\t\t                    <span class=\"add-on\"><i class=\"icon-calendar\"></i></span>\r\n");
      out.write("\t\t\t                \t</div>\r\n");
      out.write("\t\t\t                </div>\r\n");
      out.write("\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"control-group\">\r\n");
      out.write("\t\t\t                <label class=\"control-label\">任务截止时间</label>\r\n");
      out.write("\t\t\t                <div class=\"controls input-group date\" name=\"taskEndTime\" >\r\n");
      out.write("\t\t\t                    <div class=\"input-prepend input-append\">\r\n");
      out.write("\t\t\t\t                    <input name=\"taskEndTime\" class=\"form-control\" size=\"16\" type=\"text\" readonly=\"readonly\">\r\n");
      out.write("\t\t\t\t                    <span class=\"input-group-addon\"><span class=\"glyphicon glyphicon-remove\"></span></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"input-group-addon\"><span class=\"glyphicon glyphicon-calendar\"></span></span>\r\n");
      out.write("\t\t\t\t                    <span class=\"add-on\"><i class=\"icon-calendar\"></i></span>\r\n");
      out.write("\t\t\t                \t</div>\r\n");
      out.write("\t\t\t                </div>\r\n");
      out.write("\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t        \r\n");
      out.write("\t\t\t\t        <div class=\"control-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"control-label\">发起人</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"controls\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"spEmployeeRealName\" class=\"span6\" readonly=\"readonly\"> \r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t        <div class=\"control-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"control-label\">执行人员</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"controls\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"reEmployeeRealName\" class=\"span6\" readonly=\"readonly\"> \r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"control-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"control-label\">反馈</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"controls\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<textarea name=\"feedbackDetail\" class=\"span6 ckeditor\" rows=\"6\" required></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-actions\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-success\">保存</button>\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"button\" class=\"btn\" onclick=\"refreshTaskInfos();\">取消</button>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"reset\" value=\"Reset\" class=\"hidden\"/>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<!-- 时间轴 begin  -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"timeline-messages\" data-timeLine=\"feedback\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"msg-time-chat\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"message-body msg-in\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"arrow\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p class=\"attribution\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\" >Jhon Doe</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tat 1:55pm, 13th April 2013\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>Hello, How are you brother?</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"msg-time-chat\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"message-body msg-out\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"arrow\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p class=\"attribution\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\">Jonathan Smith</a> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tat 2:01pm, 13th April 2013\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>I'm Fine, Thank you. What about you? How is going on?</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"msg-time-chat\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"message-body msg-in\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"arrow\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p class=\"attribution\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\">Jhon Doe</a> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tat 2:03pm, 13th April 2013\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>Yeah I'm fine too. Everything is going fine here.</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"msg-time-chat\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"message-body msg-out\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"arrow\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p class=\"attribution\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\">Jonathan Smith</a> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tat 2:05pm, 13th April 2013\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\twell good to know that. anyway how much time you need to done your task?\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- /时间轴 /end -->\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- /任务反馈 /end -->\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\tinitReceiveTaskInfo();\r\n");
      out.write("\t})\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
