/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.75
 * Generated at: 2017-04-20 13:56:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.login;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import cn.com.noomn.util.RSAModel;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/Util/jsp/securityRSA.jsp", Long.valueOf(1492693402886L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("<meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("<meta http-equiv=\"expires\" content=\"0\">\r\n");
      out.write("\r\n");
      out.write("<title>登录</title>\r\n");
      out.write("\r\n");
      out.write("\t<!-- jquery -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/Util/js/jquery/jquery.2.1.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- bootstrap & fontawesome -->\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/Util/js/bootstrap-3.3.7-dist/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/Util/js/bootstrap-3.3.7-dist/css/bootstrap.min.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/login/fonts/font-awesome/4.2.0/css/font-awesome.min.css\"/>\r\n");
      out.write("\r\n");
      out.write("    <!-- text fonts -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/login/fonts/fonts-googleapis/fonts.googleapis.com.css\"/>\r\n");
      out.write("\r\n");
      out.write("    <!-- ace styles -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/login/css/ace.min.css\"/>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/Util/js/bootstrapValidator0.5.2/css/bootstrapValidator.min.css\">\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/Util/js/bootstrapValidator0.5.2/js/bootstrapValidator.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/Util/js/bootstrapValidator0.5.2/js/language/zh_CN.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/Util/js/security.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/Util/js/craftpip-jquery-confirm-e3e217e/css/jquery-confirm.css\">\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/Util/js/craftpip-jquery-confirm-e3e217e/js/jquery-confirm.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- MyUtil.js -->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/Util/js/util.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 安全校验 -->\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");

RSAModel rsaModel = RSAModel.getRSAModelInstance();
request.setAttribute("publicExponent", rsaModel.getPublicExponent());
request.setAttribute("publicKeyModulus", rsaModel.getPublicKeyModulus());
session.setAttribute("privateExponent", rsaModel.getPrivateExponent());
session.setAttribute("privateKeyModulus", rsaModel.getPrivateKeyModulus());

      out.write("\r\n");
      out.write("\t<!-- 模态弹出框 -->\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"login-layout\">\r\n");
      out.write("<div class=\"main-container\">\r\n");
      out.write("    <div class=\"main-content\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-sm-10 col-sm-offset-1\">\r\n");
      out.write("                <div class=\"login-container\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"space-12\"></div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"center\">\r\n");
      out.write("                        <h1>\r\n");
      out.write("                            <i class=\"ace-icon fa fa-leaf green\"></i>\r\n");
      out.write("                            <span class=\"red\">CRM</span>\r\n");
      out.write("                            <span class=\"white\" id=\"id-text2\">客户关系</span>\r\n");
      out.write("                        </h1>\r\n");
      out.write("                        <h4 class=\"blue\" id=\"id-company-text\">noomn.com</h4>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"space-6\"></div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t<!-- .position-relative begin -->\r\n");
      out.write("                    <div class=\"position-relative\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- 用户登录 begin -->\r\n");
      out.write("                        <!-- login-box-->\r\n");
      out.write("                        <div id=\"login-box\" class=\"login-box visible widget-box no-border\">\r\n");
      out.write("                            <div class=\"widget-body\">\r\n");
      out.write("                                <div class=\"widget-main\">\r\n");
      out.write("                                    <h4 class=\"header blue lighter bigger\">\r\n");
      out.write("                                        <i class=\"ace-icon fa fa-coffee green\"></i>\r\n");
      out.write("                                        \t请输入您的信息\r\n");
      out.write("                                    </h4>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"space-6\"></div>\r\n");
      out.write("\r\n");
      out.write("                                    <!-- 登录表单 -->\r\n");
      out.write("                                    <form data-form=\"loginBoxForm\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/logins/login\" method=\"post\">\r\n");
      out.write("                                        <!-- 用户名 -->\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <div class=\"input-group\">\r\n");
      out.write("                                                <span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-user\"></i></span>\r\n");
      out.write("                                                <input type=\"text\" class=\"form-control\" placeholder=\"用户名..\" name=\"employeeUsername\" value=\"liangbozhao\" />\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div><!-- /用户名 -->\r\n");
      out.write("\r\n");
      out.write("                                        <!-- 密码 -->\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <div class=\"input-group\">\r\n");
      out.write("                                                <span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-lock\"></i></span>\r\n");
      out.write("                                                <input type=\"password\" class=\"form-control\" placeholder=\"密码..\" name=\"password\" value=\"123456\" />\r\n");
      out.write("                                                <input type=\"hidden\" name=\"employeeRSAPassword\"/>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div><!-- /密码 -->\r\n");
      out.write("\r\n");
      out.write("                                        <div class=\"space\"></div>\r\n");
      out.write("\r\n");
      out.write("                                            <div class=\"clearfix\">\r\n");
      out.write("                                            \t\r\n");
      out.write("                                                <button data-submit=\"submitButton\" data-formName=\"loginBoxForm\" type=\"button\" class=\"width-35 pull-right btn btn-sm btn-primary\">\r\n");
      out.write("                                                    <i class=\"ace-icon fa fa-key\"></i>\r\n");
      out.write("                                                    <span class=\"bigger-110\">登录</span>\r\n");
      out.write("                                                </button>\r\n");
      out.write("                                            </div>\r\n");
      out.write("\r\n");
      out.write("                                            <div class=\"space-4\"></div>\r\n");
      out.write("                                    </form><!-- /登录表单 -->\r\n");
      out.write("\r\n");
      out.write("                                </div><!-- /.widget-main -->\r\n");
      out.write("                                \r\n");
      out.write("                                <div class=\"toolbar clearfix mytoolbar center\">\r\n");
      out.write("                                    <a href=\"#\" data-target=\"#forgot-box\" class=\"forgot-password-link\">\r\n");
      out.write("                                        <i class=\"ace-icon fa fa-arrow-left\"></i>\r\n");
      out.write("                                       \t 忘记密码\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                \r\n");
      out.write("                            </div><!-- /.widget-body -->\r\n");
      out.write("                        </div><!-- /.login-box -->\r\n");
      out.write("                        <!-- 用户登录 /end -->\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<!-- 找回密码 begin -->\r\n");
      out.write("                        <div id=\"forgot-box\" class=\"forgot-box widget-box no-border\">\r\n");
      out.write("                            <div class=\"widget-body\">\r\n");
      out.write("                                <div class=\"widget-main\">\r\n");
      out.write("                                    <h4 class=\"header red lighter bigger\">\r\n");
      out.write("                                        <i class=\"ace-icon fa fa-key\"></i>\r\n");
      out.write("                                        \t重置密码\r\n");
      out.write("                                    </h4>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"space-6\"></div>\r\n");
      out.write("                                    <p>\r\n");
      out.write("                                       \t 输入您的电子邮件和接收指令\r\n");
      out.write("                                    </p>\r\n");
      out.write("\r\n");
      out.write("                                    <!--  找回密码表单 -->\r\n");
      out.write("                                    <form data-form=\"forgotBoxForm\" action=\"#\">\r\n");
      out.write("                                    \t\r\n");
      out.write("                                    \t<!-- employeeUsername -->\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <div class=\"input-group\">\r\n");
      out.write("                                                <span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-user\"></i></span>\r\n");
      out.write("                                                <input name=\"employeeUsername\" type=\"text\" class=\"form-control\" placeholder=\"用户名..\" />\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div><!-- /employeeUsername -->\r\n");
      out.write("                                    \r\n");
      out.write("                                        <!-- email -->\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <div class=\"input-group\">\r\n");
      out.write("                                                <span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-envelope\"></i></span>\r\n");
      out.write("                                                <input name=\"employeeEmail\" type=\"email\" class=\"form-control\" placeholder=\"Email..\" />\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div><!-- /email -->\r\n");
      out.write("                                        \r\n");
      out.write("                                        <!-- employeeInstruct -->\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <div class=\"input-group\">\r\n");
      out.write("                                                <span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-wrench\"></i></span>\r\n");
      out.write("                                                <input name=\"employeeInstruct\" type=\"text\" class=\"form-control\" placeholder=\"验证码..\" />\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div><!-- /employeeInstruct -->\r\n");
      out.write("                                        \r\n");
      out.write("                                        <div class=\"clearfix\">\r\n");
      out.write("                                        \t<button data-sendEmail=\"sendEmailButton\" onclick=\"sendEmailForResetPassword(30);\" type=\"button\" class=\"width-48 pull-left btn btn-sm btn-danger\">\r\n");
      out.write("                                                <i class=\"ace-icon fa fa-lightbulb-o\"></i>\r\n");
      out.write("                                                <span data-sendEmail=\"sendEmailButtonSpan\" class=\"bigger-110\">发送邮件</span>\r\n");
      out.write("                                            </button>\r\n");
      out.write("                                        \t<button onclick=\"resetPassword();\" data-submit=\"submitButton\" type=\"button\" class=\"width-48 pull-right btn btn-sm btn-danger\">\r\n");
      out.write("                                                <i class=\"ace-icon fa fa-lightbulb-o\"></i>\r\n");
      out.write("                                                <span data-submitButtonSpan=\"data-submitButtonSpan\" class=\"bigger-110\">重置密码</span>\r\n");
      out.write("                                            </button>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </form><!--  找回密码表单 -->\r\n");
      out.write("                                </div><!-- /.widget-main -->\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"toolbar center\">\r\n");
      out.write("                                    <a href=\"#\" data-target=\"#login-box\" class=\"back-to-login-link\">\r\n");
      out.write("                                       \t 返回登录\r\n");
      out.write("                                        <i class=\"ace-icon fa fa-arrow-right\"></i>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div><!-- /.widget-body -->\r\n");
      out.write("                        </div><!-- /.forgot-box -->\r\n");
      out.write("                        <!-- 找回密码 /end -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- 用户注册 begin-->\r\n");
      out.write("                        <div id=\"signup-box\" class=\"signup-box widget-box no-border\">\r\n");
      out.write("                            <div class=\"widget-body\">\r\n");
      out.write("                                <div class=\"widget-main\">\r\n");
      out.write("                                    <h4 class=\"header green lighter bigger\">\r\n");
      out.write("                                        <i class=\"ace-icon fa fa-users blue\"></i>\r\n");
      out.write("                                       \t 用户注册\r\n");
      out.write("                                    </h4>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"space-6\"></div>\r\n");
      out.write("                                    <p>填写信息: </p>\r\n");
      out.write("\r\n");
      out.write("                                    <!-- 注册表单 -->\r\n");
      out.write("                                    <form data-form=\"signupBoxForm\">\r\n");
      out.write("                                        <!-- email -->\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <div class=\"input-group\">\r\n");
      out.write("                                                <span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-envelope\"></i></span>\r\n");
      out.write("                                                <input name=\"email\" type=\"email\" class=\"form-control\" placeholder=\"Email..\"  />\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div><!-- /email -->\r\n");
      out.write("\r\n");
      out.write("                                        <!-- 用户名 -->\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <div class=\"input-group\">\r\n");
      out.write("                                                <span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-user\"></i></span>\r\n");
      out.write("                                                <input name=\"username\" type=\"text\" class=\"form-control\" placeholder=\"用户名..\" />\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div><!-- /用户名 -->\r\n");
      out.write("\r\n");
      out.write("                                        <!-- 密码 -->\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <div class=\"input-group\">\r\n");
      out.write("                                                <span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-lock\"></i></span>\r\n");
      out.write("                                                <input name=\"password\" type=\"password\" class=\"form-control\" placeholder=\"密码..\"  />\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div><!-- /密码 -->\r\n");
      out.write("\r\n");
      out.write("                                        <!-- 确认密码 -->\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <div class=\"input-group\">\r\n");
      out.write("                                                <span class=\"input-group-addon\"><i class=\"fa fa-retweet\"></i></span>\r\n");
      out.write("                                                <input name=\"confirmPassword\" type=\"password\" class=\"form-control\" placeholder=\"确认密码..\"  />\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div><!-- /确认密码 -->\r\n");
      out.write("\r\n");
      out.write("                                            <label class=\"block\">\r\n");
      out.write("                                                <input type=\"checkbox\" class=\"ace\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"lbl\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t接受\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"#\">用户协议</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</span>\r\n");
      out.write("                                            </label>\r\n");
      out.write("\r\n");
      out.write("                                            <div class=\"space-8\"></div>\r\n");
      out.write("\r\n");
      out.write("                                            <div class=\"clearfix\">\r\n");
      out.write("                                                <button data-reset=\"resetButton\" type=\"reset\" class=\"width-30 pull-left btn btn-sm\">\r\n");
      out.write("                                                    <i class=\"ace-icon fa fa-refresh\"></i>\r\n");
      out.write("                                                    <span class=\"bigger-110\">重置</span>\r\n");
      out.write("                                                </button>\r\n");
      out.write("\r\n");
      out.write("                                                <button data-submit=\"submitButton\" type=\"button\" class=\"width-65 pull-right btn btn-sm btn-success\">\r\n");
      out.write("                                                    <span class=\"bigger-110\">注册</span>\r\n");
      out.write("                                                    <i class=\"ace-icon fa fa-arrow-right icon-on-right\"></i>\r\n");
      out.write("                                                </button>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                    </form><!-- /注册表单 -->\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"toolbar center\">\r\n");
      out.write("                                    <a href=\"#\" data-target=\"#login-box\" class=\"back-to-login-link\">\r\n");
      out.write("                                        <i class=\"ace-icon fa fa-arrow-left\"></i>\r\n");
      out.write("                                        \t返回登录\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div><!-- /.widget-body -->\r\n");
      out.write("                        </div><!-- /.signup-box -->\r\n");
      out.write("                        <!-- 用户注册 /end-->\r\n");
      out.write("                        \r\n");
      out.write("                    </div><!-- /.position-relative -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- 主题 begin -->\r\n");
      out.write("                    <div class=\"navbar-fixed-top align-right\">\r\n");
      out.write("                        <br/>\r\n");
      out.write("                        &nbsp;\r\n");
      out.write("                        <a id=\"btn-login-dark\" href=\"#\">Dark</a>\r\n");
      out.write("                        &nbsp;\r\n");
      out.write("                        <span class=\"blue\">/</span>\r\n");
      out.write("                        &nbsp;\r\n");
      out.write("                        <a id=\"btn-login-blur\" href=\"#\">Blur</a>\r\n");
      out.write("                        &nbsp;\r\n");
      out.write("                        <span class=\"blue\">/</span>\r\n");
      out.write("                        &nbsp;\r\n");
      out.write("                        <a id=\"btn-login-light\" href=\"#\">Light</a>\r\n");
      out.write("                        &nbsp; &nbsp; &nbsp;\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- 主题 /end -->\r\n");
      out.write("                </div>\r\n");
      out.write("            </div><!-- /.col -->\r\n");
      out.write("        </div><!-- /.row -->\r\n");
      out.write("    </div><!-- /.main-content -->\r\n");
      out.write("</div><!-- /.main-container -->\r\n");
      out.write("\r\n");
      out.write("<!-- inline scripts related to this page -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("    jQuery(function ($) {\r\n");
      out.write("        $(document).on('click', '.toolbar a[data-target]', function (e) {\r\n");
      out.write("            e.preventDefault();\r\n");
      out.write("            var target = $(this).data('target');\r\n");
      out.write("            $('.widget-box.visible').removeClass('visible');//hide others\r\n");
      out.write("            $(target).addClass('visible');//show target\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    //you don't need this, just used for changing background\r\n");
      out.write("    jQuery(function ($) {\r\n");
      out.write("        $('#btn-login-dark').on('click', function (e) {\r\n");
      out.write("            $('body').attr('class', 'login-layout');\r\n");
      out.write("            $('#id-text2').attr('class', 'white');\r\n");
      out.write("            $('#id-company-text').attr('class', 'blue');\r\n");
      out.write("        });\r\n");
      out.write("        $('#btn-login-light').on('click', function (e) {\r\n");
      out.write("            $('body').attr('class', 'login-layout light-login');\r\n");
      out.write("            $('#id-text2').attr('class', 'grey');\r\n");
      out.write("            $('#id-company-text').attr('class', 'blue');\r\n");
      out.write("        });\r\n");
      out.write("        $('#btn-login-blur').on('click', function (e) {\r\n");
      out.write("            $('body').attr('class', 'login-layout blur-login');\r\n");
      out.write("            $('#id-text2').attr('class', 'white');\r\n");
      out.write("            $('#id-company-text').attr('class', 'light-blue');\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    var option =\r\n");
      out.write("    {\r\n");
      out.write("        message: 'This value is not valid',\r\n");
      out.write("        feedbackIcons:{\r\n");
      out.write("            valid: 'glyphicon glyphicon-ok',\r\n");
      out.write("            invalid:'glyphicon glyphicon-remove',\r\n");
      out.write("            validating:'glyphicon glyphicon-refresh'\r\n");
      out.write("        },\r\n");
      out.write("        fields: {\r\n");
      out.write("        \temployeeEmail: {\r\n");
      out.write("                validators: {\r\n");
      out.write("                    notEmpty: {\r\n");
      out.write("                        message: '请输入邮箱'\r\n");
      out.write("                    },\r\n");
      out.write("                    emailAddress: {\r\n");
      out.write("                        message: '请输入正确的邮件地址'\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            },\r\n");
      out.write("            employeeInstruct: {\r\n");
      out.write("                validators: {\r\n");
      out.write("                    notEmpty: {\r\n");
      out.write("                        message: '请输入验证码'\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            },\r\n");
      out.write("            employeeUsername: {\r\n");
      out.write("                validators: {\r\n");
      out.write("                    notEmpty: {\r\n");
      out.write("                        message: ' 用户名不能为空'\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            },\r\n");
      out.write("            password: {\r\n");
      out.write("                validators: {\r\n");
      out.write("                    notEmpty: {\r\n");
      out.write("                        message: '密码不能为空'\r\n");
      out.write("                    },\r\n");
      out.write("                }\r\n");
      out.write("            },\r\n");
      out.write("            confirmPassword: {\r\n");
      out.write("                validators: {\r\n");
      out.write("                    notEmpty: {message: '请再次输入密码'},\r\n");
      out.write("                    identical: {  //比较是否相同\r\n");
      out.write("                        field: 'password',  //需要进行比较的input name值\r\n");
      out.write("                        message: '两次密码不一致'\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            },\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write(" \r\n");
      out.write("    $(function() {\r\n");
      out.write("        var $form = $(\"form\");\r\n");
      out.write("        $form.bootstrapValidator(option);\r\n");
      out.write("    })\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t//提交: 登录按钮\r\n");
      out.write("\t$('form[data-form=\"loginBoxForm\"]').find(':button[data-submit=\"submitButton\"]').click(function() {\r\n");
      out.write("\t\tvar passwordVal = $('form[data-form=\"loginBoxForm\"]').find(':input[name=\"password\"]').val();\r\n");
      out.write("\t\tvar publicKeyModulus = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${publicKeyModulus}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\";\r\n");
      out.write("\t\tvar publicExponent = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${publicExponent}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\";\r\n");
      out.write("\t\tpasswordVal = encryptRSA(publicKeyModulus, publicExponent, passwordVal);\r\n");
      out.write("\t\t$('form[data-form=\"loginBoxForm\"]').find(':input[name=\"employeeRSAPassword\"]').val(passwordVal);\r\n");
      out.write("\t\t$('form[data-form=\"loginBoxForm\"]').find(':button[type=\"submit\"]').click();\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t//消息提示\r\n");
      out.write("\tshowInfos(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${infos}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\", \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${infos.message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\", \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${infos.obj}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\", \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\");\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\t//封装一个加密方法，m对应modulus，e对应public exponent，text是明文\r\n");
      out.write("\tfunction encryptRSA(m, e, text) {\r\n");
      out.write("\t\tvar key = RSAUtils.getKeyPair(e, '', m);\r\n");
      out.write("\t\treturn RSAUtils.encryptedString(key, text);\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\t//倒计时\r\n");
      out.write("\tvar timeID = 0;\r\n");
      out.write("\tfunction timeDown(timeNow) {\r\n");
      out.write("\t\tif(--timeNow >= 0) {\r\n");
      out.write("\t\t\tvar $sendEmailButtonSpan = $('span[data-sendEmail=\"sendEmailButtonSpan\"]');\r\n");
      out.write("\t\t\t$sendEmailButtonSpan.html(timeNow + \"秒后再次发送\");\r\n");
      out.write("\t\t\ttimeID = setTimeout(function() { \r\n");
      out.write("\t\t\t\ttimeDown(timeNow);\r\n");
      out.write("\t        }, \r\n");
      out.write("\t        1000);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t//发送邮件\r\n");
      out.write("\tfunction sendEmailForResetPassword(timeNow) {\r\n");
      out.write("\t\t$form = $('form[data-form=\"forgotBoxForm\"]');\r\n");
      out.write("\t\t$form.data('bootstrapValidator').resetForm();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t$form = $('form[data-form=\"forgotBoxForm\"]');\r\n");
      out.write("\t\tvar isTrue = false;\r\n");
      out.write("\t\t$form.data(\"bootstrapValidator\").validateField('employeeUsername');\r\n");
      out.write("\t\t$form.data(\"bootstrapValidator\").validateField('employeeEmail');\r\n");
      out.write("\t\tisTrue = $form.data(\"bootstrapValidator\").isValidField('employeeUsername');\r\n");
      out.write("\t\tif (isTrue == false) return;\r\n");
      out.write("\t\tisTrue = $form.data(\"bootstrapValidator\").isValidField('employeeEmail');\r\n");
      out.write("\t\tif (isTrue == false) return;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar $sendEmailButton = $(':button[data-sendEmail=\"sendEmailButton\"]');\r\n");
      out.write("\t\tvar $sendEmailButtonSpan = $('span[data-sendEmail=\"sendEmailButtonSpan\"]');\r\n");
      out.write("\t\t$('form[data-form=\"forgotBoxForm\"]').find(\":input\").attr(\"disabled\", true);\r\n");
      out.write("\t\t$('form[data-form=\"forgotBoxForm\"]').find(\":button\").attr(\"disabled\", true);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar employeeUsernameVal = $form.find(':input[name=\"employeeUsername\"]').val();\r\n");
      out.write("\t\tvar employeeEmailVal = $form.find(':input[name=\"employeeEmail\"]').val();\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/logins/sendEmailForResetPassword\",\r\n");
      out.write("\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\tdata : {\r\n");
      out.write("\t\t\t\temployeeUsername : employeeUsernameVal,\r\n");
      out.write("\t\t\t\temployeeEmail : employeeEmailVal\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tbeforeSend : function() {\r\n");
      out.write("\t\t\t\t$sendEmailButtonSpan.html(timeNow  + \"秒后再次发送\" );\r\n");
      out.write("\t\t\t\ttimeDown(timeNow);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tcomplete: function(){\r\n");
      out.write("\t\t\t\tclearTimeout(timeID);\r\n");
      out.write("\t\t\t\tvar $sendEmailButton = $(':button[data-sendEmail=\"sendEmailButton\"]');\r\n");
      out.write("\t\t\t\tvar $sendEmailButtonSpan = $('span[data-sendEmail=\"sendEmailButtonSpan\"]');\r\n");
      out.write("\t\t\t\t$sendEmailButtonSpan.html(\"发送邮件\");\r\n");
      out.write("\t\t\t\t$('form[data-form=\"forgotBoxForm\"]').find(\":input\").removeAttr(\"disabled\");\r\n");
      out.write("\t\t\t\t$('form[data-form=\"forgotBoxForm\"]').find(\":button\").removeAttr(\"disabled\");\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\tsetAlertModalTitleAndBody(\"发送邮件\", data.obj);\r\n");
      out.write("\t\t\t\t$('div[data-Modal=\"alertModal\"]').modal('show');\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function() {\r\n");
      out.write("\t\t\t\ttimeNow = 0;\r\n");
      out.write("\t\t\t\tclearTimeout(timeID);\r\n");
      out.write("\t\t\t\tsetAlertModalTitleAndBody(\"发送邮件\", \"发送失败，我们会尽快修复该问题。\");\r\n");
      out.write("\t\t\t\t$('div[data-Modal=\"alertModal\"]').modal('show');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t//重置密码\r\n");
      out.write("\tfunction resetPassword() {\r\n");
      out.write("\t\t$form = $('form[data-form=\"forgotBoxForm\"]');\r\n");
      out.write("\r\n");
      out.write("\t\tvar isTrue = $form.bootstrapValidator('validate').data('bootstrapValidator').isValid();\r\n");
      out.write("\t\tif (isTrue == false) return;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('form[data-form=\"forgotBoxForm\"]').find('span[data-submitButtonSpan=\"data-submitButtonSpan\"]').html(\"正在重置\");\r\n");
      out.write("\t\t$('form[data-form=\"forgotBoxForm\"]').find(\":input\").attr(\"disabled\", true);\r\n");
      out.write("\t\t$('form[data-form=\"forgotBoxForm\"]').find(\":button\").attr(\"disabled\", true);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar employeeUsernameVal = $form.find(':input[name=\"employeeUsername\"]').val();\r\n");
      out.write("\t\tvar employeeEmailVal = $form.find(':input[name=\"employeeEmail\"]').val();\r\n");
      out.write("\t\tvar employeeInstructVal = $form.find(':input[name=\"employeeInstruct\"]').val();\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\tasync: true,\r\n");
      out.write("\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/logins/resetPassword\",\r\n");
      out.write("\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\tdata : {\r\n");
      out.write("\t\t\t\temployeeUsername : employeeUsernameVal,\r\n");
      out.write("\t\t\t\temployeeEmail : employeeEmailVal,\r\n");
      out.write("\t\t\t\temployeeInstruct : employeeInstructVal\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\tsetAlertModalTitleAndBody(\"发送邮件\", data.obj);\r\n");
      out.write("\t\t\t\t$('div[data-Modal=\"alertModal\"]').modal('show');\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$('form[data-form=\"forgotBoxForm\"]').find(':button[data-submit=\"submitButton\"]').removeAttr(\"disabled\");\r\n");
      out.write("\t\t\t\t$('form[data-form=\"forgotBoxForm\"]').find('span[data-submitButtonSpan=\"data-submitButtonSpan\"]').html(\"重置密码\");\r\n");
      out.write("\t\t\t\t$(':button[data-sendEmail=\"sendEmailButton\"]').removeAttr(\"disabled\");\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function() {\r\n");
      out.write("\t\t\t\tsetAlertModalTitleAndBody(\"发送邮件\", \"发送失败，我们会尽快修复该问题。\");\r\n");
      out.write("\t\t\t\t$('div[data-Modal=\"alertModal\"]').modal('show');\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t$('form[data-form=\"forgotBoxForm\"]').find(':button[data-submit=\"submitButton\"]').removeAttr(\"disabled\");\r\n");
      out.write("\t\t\t\t$('form[data-form=\"forgotBoxForm\"]').find('span[data-submitButtonSpan=\"data-submitButtonSpan\"]').html(\"重置密码\");\r\n");
      out.write("\t\t\t\t$(':button[data-sendEmail=\"sendEmailButton\"]').removeAttr(\"disabled\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
